Create README.md
hkirat/linkedin-bot pull request #6
Opened 2023-03-04 23:19 UTC by x0samnan

2023-03-04 23:20 UTC, x0samnan commented
Another PR for readme is already opened. This will be closed.

2023-03-05 00:32 UTC, x0samnan commented
@hkirat Please, have a look at this PR. Let me know, if there are any changes to be made.

2023-03-05 08:27 UTC, laukik-target commented on README.md
> +4) Install selenium and dotenv using "npm i selenium dotenv"
Better to "cd " into the project root and run "npm i". 

This way in the future if any new dep added no need to update README

2023-03-05 08:30 UTC, laukik-target commented on README.md
> +5) Run the application.
A better way to run on AWS is using pm2 

checkout: [](https://pm2.keymetrics.io/)

2023-03-05 08:45 UTC, x0samnan commented on README.md
> +4) Install selenium and dotenv using "npm i selenium dotenv"
@laukik-target Will change the code but since we are making a .env file in first case, I think dotenv has to be manually installed.

2023-03-05 14:10 UTC, x0samnan commented
@hkirat Are there any more changes required or is the PR ready to be merged?

2023-03-05 14:43 UTC, cleverhare requested changes
It actually looks good but a sort of screenshot of the bot working fine is what missing in this readme so if you add on that it will be a nice readme

2023-03-05 14:51 UTC, x0samnan commented
@cleverhare Thanks for the suggestion. Actually, to show the working of bot, a screenshot would not be enough so a video would be rather great. If you don't mind, can you work on that bit after this PR gets merged?

2023-03-05 15:14 UTC, cleverhare commented
Yeah we can work together no worries

2023-03-06 04:57 UTC, x0samnan commented
@hkirat Is this Readme PR ready to be merged or are there any changes required?

2023-03-06 05:54 UTC, cleverhare requested changes
Please don't share your credentials.  Add the .env file to the gitignore file

2023-03-06 06:10 UTC, x0samnan commented
@cleverhare Is my .env pushed?

2023-03-06 06:46 UTC, cleverhare commented
Yes it is pushed, Change the Password and do add it in gitignore file

2023-03-06 10:07 UTC, x0samnan commented
@cleverhare I can't see it on my end. I will close this and open a new PR.

2023-03-06 10:07 UTC, closed without merging

2023-03-06 10:08 UTC, cleverhare commented
Okay

2023-03-06 10:18 UTC, x0samnan commented
@cleverhare Refer to #11 for working on it.